package id.ac.mi.poliban.diana.customlistview;

import java.util.ArrayList;
import java.util.List;

public class CountryData {
    static List<Country> getAllData(){
        List<Country> data = new ArrayList<>();
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/125px-Flag_of_Thailand.svg.png", "Thailand", "Thailand,[a] officially the Kingdom of Thailand and formerly known as Siam,[b] is a country at the centre of the Southeast Asian Indochinese peninsula composed of 76 provinces. At 513,120 km2 (198,120 sq mi) and over 68 million people, Thailand is the world's 50th-largest country by total area and the 22nd-most-populous country. The capital and largest city is Bangkok, a special administrative area. Thailand is bordered to the north by Myanmar and Laos, to the east by Laos and Cambodia, to the south by the Gulf of Thailand and Malaysia, and to the west by the Andaman Sea and the southern extremity of Myanmar. Its maritime boundaries include Vietnam in the Gulf of Thailand to the southeast, and Indonesia and India on the Andaman Sea to the southwest. It is a unitary state. Although nominally the country is a constitutional monarchy and parliamentary democracy, the most recent coup, in 2014, established a de facto military dictatorship under a junta."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/125px-Flag_of_France.svg.png", "France", "France (French: [fʁɑ̃s] (About this soundlisten)), officially the French Republic (French: République française, pronounced [ʁepyblik fʁɑ̃sɛːz] (About this soundlisten)), is a country whose territory consists of metropolitan France in Western Europe and several overseas regions and territories.[XIII] The metropolitan area of France extends from the Mediterranean Sea to the English Channel and the North Sea, and from the Rhine to the Atlantic Ocean. It is bordered by Belgium, Luxembourg and Germany to the northeast, Switzerland and Italy to the east, and Andorra and Spain to the south. The overseas territories include French Guiana in South America and several islands in the Atlantic, Pacific and Indian oceans. The country's 18 integral regions (five of which are situated overseas) span a combined area of 643,801 square kilometres (248,573 sq mi) and a total population of 67.02 million (as of July 2019).[10] France is a unitary semi-presidential republic with its capital in Paris, the country's largest city and main cultural and commercial centre. Other major urban areas include Lyon, Marseille, Toulouse, Bordeaux, Lille and Nice."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png", "Indonesia", "Indonesia (/ˌɪndəˈniːʒə/ (About this soundlisten) IN-də-NEE-zhə, /-ˈniːziə/ -\u2060NEE-zee-ə; Indonesian: [ɪndoˈnesia]), officially the Republic of Indonesia (Indonesian: Republik Indonesia [reˈpublik ɪndoˈnesia]),[a] is a country in Southeast Asia, between the Indian and Pacific oceans. It is the world's largest island country, with more than seventeen thousand islands,[11] and at 1,904,569 square kilometres (735,358 square miles), the 14th largest by land area and 7th in the combined sea and land area.[12] With over 261 million people, it is the world's 4th most populous country as well as the most populous Muslim-majority country.[13] Java, the world's most populous island,[14] is home to more than half of the country's population."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/125px-Flag_of_Vietnam.svg.png", "Vietnam", "Vietnam (Vietnamese: Việt Nam pronounced [vîət nāːm] (About this soundlisten)), officially the Socialist Republic of Vietnam (Vietnamese: Cộng hòa xã hội chủ nghĩa Việt Nam), is the easternmost country on the Indochina Peninsula. With an estimated 94.6 million inhabitants as of 2016, it is the 15th most populous country in the world. Vietnam shares its land borders with China to the north, and Laos and Cambodia to the west. It shares its maritime borders with Thailand through the Gulf of Thailand, and the Philippines, Indonesia and Malaysia through the South China Sea.[n 4] Its capital city is Hanoi, while its most populous city is Ho Chi Minh City."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/125px-Flag_of_the_Philippines.svg.png", "Filipina", "Filipina atau Republik Filipina (bahasa Tagalog: Republika ng Pilipinas) adalah sebuah negara republik di Asia Tenggara, sebelah utara Indonesia, dan Malaysia. Filipina merupakan sebuah negara kepulauan yang terletak di Lingkar Pasifik Barat, negara ini terdiri dari 7.641 pulau. Selama ribuan tahun, warga kepulauan Filipina, dan pekerja keras ini telah mengembangkan sistem cocok tanam Padi yang sangat maju, yang menyediakan makanan pokok bagi masyarakatnya."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/125px-Flag_of_Egypt.svg.png", "Mesir", "Mesir (bahasa Arab: مصر, translit. Maṣr\u200E), nama resmi Republik Arab Mesir (bahasa Arab: جمهوريّة مصر العربيّة, translit. Jumhūriyyat Miṣr al-ʿArabiyyah\u200E, Arab Mesir: Gomhoreyyet Maṣr el-ʿArabeyya\u200E) adalah sebuah negara yang sebagian besar wilayahnya terletak di Afrika bagian timur laut. Mesir juga digolongkan sebagai negara maju di Afrika."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png", "Amerika Serikat", "Amerika Serikat, disingkat dengan AS (bahasa Inggris: United States of America/U.S.A. disingkat United States/US), atau secara umum dikenal dengan Amerika saja,[catatan 1] adalah sebuah negara republik konstitusional federal yang terdiri dari lima puluh negara bagian dan sebuah distrik federal.[7] Negara ini terletak di bagian tengah Amerika Utara, yang menjadi lokasi dari empat puluh delapan negara bagian yang saling bersebelahan, beserta distrik ibu kota Washington, D.C.. Amerika Serikat diapit oleh Samudra Pasifik dan Atlantik di sebelah barat dan timur, berbatasan dengan Kanada di sebelah utara, dan Meksiko di sebelah selatan. Dua negara bagian lainnya, yaitu Alaska dan Hawaii, terletak terpisah dari dataran utama Amerika Serikat. Negara bagian Alaska terletak di sebelah ujung barat laut Amerika Utara, berbatasan dengan Kanada di sebelah timur dan Rusia di sebelah barat, yang dipisahkan oleh Selat Bering. Sedangkan negara bagian Hawaii adalah sebuah kepulauan yang berlokasi di Samudra Pasifik. Amerika Serikat juga memiliki beberapa teritori di Pasifik dan Karibia. Dengan luas wilayah 3,79  juta mil persegi (9,83 juta km2) dan jumlah penduduk sebanyak 315 juta jiwa, Amerika Serikat merupakan negara terluas ketiga atau keempat di dunia, dan terbesar ketiga menurut jumlah penduduk. Amerika Serikat adalah salah satu negara multietnik dan multikultural di dunia. Hal tersebut muncul akibat adanya imigrasi besar-besaran dari berbagai penjuru dunia.[8] Iklim dan geografi Amerika Serikat juga sangat beragam dan negara ini menjadi tempat tinggal bagi beragam spesies."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png", "Brasil", "Republik Federatif Brasil atau Republik Federal Brasil (bahasa Portugis: República Federativa do Brasil, bahasa Inggris: Federative Republic of Brazil, bahasa Latin: Respublica Foederativa Brasiliae) adalah negara paling besar dan paling banyak penduduknya(204.5 juta jiwa pada tahun 2017[4]) di Amerika Selatan. Negara ini merupakan negara paling timur di Benua Amerika dan berbatasan dengan Pegunungan Andes dan Samudra Atlantik. Nama Brasil diambil dari nama Kayu Brasil, sejenis kayu lokal. Brasil merupakan tempat pertanian ekstensif dan hutan hujan tropis. Sebagai bekas koloni Portugal, bahasa resmi Brasil adalah bahasa Portugis. Selain itu, Brasil juga sebagai penghasil kopi terbesar di dunia."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/125px-Flag_of_Saudi_Arabia.svg.png", "Arab Saudi", "Arab Saudi[a] (Dengarkani/ˌsɔːdiː əˈreɪbiə/, Dengarkani/ˌsaʊ-/) (Arab: المملكة العربية السعودية), secara resmi di kenal sebagai Kerajaan Arab Saudi atau Kingdom of Saudi Arabia (KSA),[b] adalah sebuah negara Arab di Asia Barat yang mencakup hampir keseluruhan wilayah Semenanjung Arabia. Dengan luas wilayah kira-kira 2150000 km2 (830000 sq mi), Arab Saudi secara geografis merupakan negara terbesar ke lima di Asia dan kedua terbesar di Dunia Arab setelah Aljazair. Arab Saudi berbatasan langsung dengan Yordania dan Irak ke utara, Kuwait ke timur laut, Qatar, Bahrain, dan Uni Emirat Arab ke timur, Oman ke tenggara, dan Yaman ke selatan. Negara ini terpisah dengan Israel dan Mesir oleh Teluk Aqaba. Negara ini adalah satu-satunya negara yang memiliki dua pesisir penting, yakni Laut Merah dan Teluk Persia, dan sebagian besar wilayah Arab Saudi merupakan gurun pasir."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png", "Korea Selatan", "Republik Korea (bahasa Korea: Daehan Minguk (Hangul: 대한민국; Hanja: 大韓民國); bahasa Inggris: Republic of Korea/ROK) atau biasa dikenal sebagai Korea Selatan atau Korsel adalah sebuah negara di Asia Timur yang meliputi bagian selatan Semenanjung Korea. Di sebelah utara, Republik Korea berbataskan Korea Utara, di mana keduanya bersatu sebagai sebuah negara hingga tahun 1948. Laut Kuning di sebelah barat, Jepang berada di seberang Laut Jepang (disebut \"Laut Timur\" oleh orang-orang Korea) dan Selat Korea berada di bagian tenggara.[12] Negara ini dikenal dengan nama Hanguk (한국; 韓國).[13] oleh penduduk Korea Selatan dan disebut Namchosŏn (남조선; 南朝鮮; \"Chosŏn Selatan\") di Korea Utara. Ibu kota Korea Selatan adalah Seoul (서울)."));

        return data;
    }

}
